// <auto-generated />
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241229164050_addProductsToDb")]
    partial class addProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models2.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "ev eşyaları"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "elektronik eşyalar"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "ayakkanılar"
                        });
                });

            modelBuilder.Entity("Models2.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            Author = "Billy Spark",
                            Description = "Sodales libero ile yaşayın. Orci augue molestie praesent, euismod velit sollicitudin ac ile yaşayın. Vestibulum facilisis nibh ut ultricies sunar.\r\n\r\nArtık yaşam titremesi ipsum amet tincidunt ile oturun.",
                            ISBN = "SWD9999002",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "Zamanın Şansı"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Nancy Hoover",
                            Description = "Sodales libero ile yaşayın. Orci augue molestie praesent, euismod velit sollicitudin ac ile yaşayın. Vestibulum facilisis nibh ut ultricies sunar.\r\n\r\nArtık yaşam titremesi ipsum amet tincidunt ile oturun.",
                            ISBN = "CAW777777702",
                            ListPrice = 40.0,
                            Price = 30.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Karanlık Gökyüzü"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Julian Button",
                            Description = "Sodales libero ile yaşayın. Orci augue molestie praesent, euismod velit sollicitudin ac ile yaşayın. Vestibulum facilisis nibh ut ultricies sunar.\r\n\r\nArtık yaşam titremesi ipsum amet tincidunt ile oturun.",
                            ISBN = "RITO5555502",
                            ListPrice = 55.0,
                            Price = 50.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "Gün Batımında Kaybolmak"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Abby Muscles",
                            Description = "Sodales libero ile yaşayın. Orci augue molestie praesent, euismod velit sollicitudin ac ile yaşayın. Vestibulum facilisis nibh ut ultricies sunar.\r\n\r\nArtık yaşam titremesi ipsum amet tincidunt ile oturun.",
                            ISBN = "WS3333333302",
                            ListPrice = 70.0,
                            Price = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0,
                            Title = "Pamuk Şeker"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Ron Parker",
                            Description = "Sodales libero ile yaşayın. Orci augue molestie praesent, euismod velit sollicitudin ac ile yaşayın. Vestibulum facilisis nibh ut ultricies sunar.\r\n\r\nArtık yaşam titremesi ipsum amet tincidunt ile oturun.",
                            ISBN = "SOTJ1111111102",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Okyanusta Kaya"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Laura Phantom",
                            Description = "Sodales libero ile yaşayın. Orci augue molestie praesent, euismod velit sollicitudin ac ile yaşayın. Vestibulum facilisis nibh ut ultricies sunar.\r\n\r\nArtık yaşam titremesi ipsum amet tincidunt ile oturun.",
                            ISBN = "FOT000000002",
                            ListPrice = 25.0,
                            Price = 23.0,
                            Price100 = 20.0,
                            Price50 = 22.0,
                            Title = "Yapraklar ve Harikalar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
